export const screeNames = {
  AUTH: 'Auth',
  LOGGED_IN: 'LoggedIn',
  ROOM: 'Room',
  LOGIN: 'Login',
  PROFILE_CREATION: 'ProfileCreation',
  CHOOSE_AUTH: 'ChooseAuth',
  EMAIL_AUTH_CREATE: 'EmailAuthCreate',
  EMAIL_AUTH_RESET: 'EmailAuthReset',
  EMAIL_AUTH_MAIN: 'EmailAuthMain',
  PHONE_AUTH: 'PhoneAuth',
  PHONE_AUTH_VERIFICATION: 'PhoneAuthVerification',
  TAB_HOME: 'TabHome',
  HOME: 'Home',
  EVENTS: 'Events',
  TAB_EVENTS: 'TabEvents',
  DIRECT: 'Direct',
  TAB_DIRECT: 'TabDirect',
  PROFILE: 'Profile',
  TAB_PROFILE: 'TabProfile',
  SETTINGS: 'Settings',
  POST_CREATION: 'PostCreation',
  FILTER_POSTS: 'FilterPosts',
};
